"""Ports: what the agent tools need from the company's systems of record.

Each protocol is implemented by an adapter. ``atrium.adapters.reference`` implements all of
them over the fictional company's Postgres schema; ``docs/connectors.md`` shows how to
write an adapter for a real HRIS over HTTP.

Contract for every adapter:
- It acts **as the identity bound to the session** (``HRSession.employee_id``). A provider
  must never return data the system of record would not show to that person. The
  reference adapter gets this from Postgres RLS; an HTTP adapter gets it from delegated
  (on-behalf-of) tokens or by re-checking with the policy engine.
- Subject ids are passed explicitly so the same port serves self-service and manager
  tools, but authorization of the subject happens before the call (policy engine) and
  again inside the system of record.
"""

from __future__ import annotations

from contextlib import AbstractContextManager
from datetime import date
from typing import Protocol

from atrium.domain.models import (
    Absence,
    Address,
    BankAccount,
    BenefitBalances,
    Dependent,
    Employee,
    Enrollment,
    IncomeStatement,
    IssuedDocument,
    JobPosting,
    LeaveRequest,
    OnboardingTask,
    Payslip,
    Plan,
    PlanChangeRequest,
    PlrPayment,
    PrivateRecord,
    Reimbursement,
    SalaryEntry,
    TimeAdjustment,
    TimeMonth,
    Training,
    TrainingAssignment,
    Unit,
    VacationPeriod,
    VacationRequest,
)


class DirectoryProvider(Protocol):
    def get(self, employee_id: str) -> Employee | None: ...
    def search(self, query: str, limit: int = 5) -> list[Employee]: ...
    def reports(self, manager_id: str, chain: bool = False) -> list[Employee]: ...
    def units(self) -> list[Unit]: ...
    def by_units(self, unit_ids: list[str], include_terminated: bool = False) -> list[Employee]: ...
    def private(self, employee_id: str) -> PrivateRecord | None: ...


class VacationProvider(Protocol):
    def periods(self, employee_id: str) -> list[VacationPeriod]: ...
    def requests(self, employee_id: str) -> list[VacationRequest]: ...
    def requests_for(self, employee_ids: list[str]) -> list[VacationRequest]: ...
    def periods_for(self, employee_ids: list[str]) -> list[VacationPeriod]: ...
    def get_request(self, request_id: str) -> VacationRequest | None: ...
    def create_request(self, employee_id: str, period_id: str, start: date, days: int, sell_days: int,
                       advance_13th: bool, requested_at: date) -> VacationRequest: ...
    def set_status(self, request_id: str, status: str, decided_by: str | None, note: str | None) -> VacationRequest: ...
    def create_leave(self, employee_id: str, kind: str, start: date, days: int, note: str) -> LeaveRequest: ...
    def leaves(self, employee_id: str) -> list[LeaveRequest]: ...


class PayrollProvider(Protocol):
    def salary_history(self, employee_id: str) -> list[SalaryEntry]: ...
    def payslips(self, employee_id: str, year: int | None = None) -> list[Payslip]: ...
    def payslip(self, employee_id: str, month: str, kind: str = "monthly") -> Payslip | None: ...
    def income_statement(self, employee_id: str, year: int) -> IncomeStatement | None: ...
    def plr(self, employee_id: str) -> list[PlrPayment]: ...


class BenefitsProvider(Protocol):
    def plans(self) -> list[Plan]: ...
    def enrollments(self, employee_id: str) -> list[Enrollment]: ...
    def dependents(self, employee_id: str) -> list[Dependent]: ...
    def balances(self, employee_id: str) -> BenefitBalances | None: ...
    def plan_changes(self, employee_id: str) -> list[PlanChangeRequest]: ...
    def request_plan_change(self, employee_id: str, from_plan: str, to_plan: str, effective: date, reason: str) -> PlanChangeRequest: ...
    def add_dependent(self, employee_id: str, name: str, relationship: str, birth_date: date, ir_dependent: bool,
                      health_plan: bool, status: str) -> Dependent: ...
    def enroll_dependent(self, employee_id: str, dependent_id: str) -> None: ...


class TimeTrackingProvider(Protocol):
    def months(self, employee_id: str) -> list[TimeMonth]: ...
    def months_for(self, employee_ids: list[str]) -> list[TimeMonth]: ...
    def adjustments(self, employee_id: str) -> list[TimeAdjustment]: ...
    def request_adjustment(self, employee_id: str, day: date, time: str, kind: str, reason: str) -> TimeAdjustment: ...
    def absences_for(self, employee_ids: list[str]) -> list[Absence]: ...


class ReimbursementProvider(Protocol):
    def list(self, employee_id: str) -> list[Reimbursement]: ...
    def create(self, employee_id: str, category: str, amount: float, day: date, merchant: str, cnpj: str,
               description: str, submitted_at: date) -> Reimbursement: ...


class ProfileProvider(Protocol):
    def address(self, employee_id: str) -> Address | None: ...
    def bank_account(self, employee_id: str) -> BankAccount | None: ...
    def update_address(self, employee_id: str, address: dict) -> Address: ...
    def update_bank_account(self, employee_id: str, account: dict, when: date) -> BankAccount: ...


class CareerProvider(Protocol):
    def trainings(self) -> list[Training]: ...
    def assignments(self, employee_id: str) -> list[TrainingAssignment]: ...
    def assignments_for(self, employee_ids: list[str]) -> list[TrainingAssignment]: ...
    def learning_paths(self) -> list[dict]: ...
    def review_cycle(self) -> dict | None: ...
    def job_postings(self) -> list[JobPosting]: ...
    def skills(self, employee_id: str) -> list[str]: ...


class OnboardingProvider(Protocol):
    def tasks(self, employee_id: str) -> list[OnboardingTask]: ...
    def buddy(self, employee_id: str) -> Employee | None: ...
    def complete_task(self, employee_id: str, task_id: str) -> OnboardingTask: ...


class DocumentsProvider(Protocol):
    def record(self, employee_id: str, kind: str, params: dict) -> IssuedDocument: ...


class HRSession(Protocol):
    """All ports bound to one identity-scoped unit of work."""

    employee_id: str
    directory: DirectoryProvider
    vacation: VacationProvider
    payroll: PayrollProvider
    benefits: BenefitsProvider
    time: TimeTrackingProvider
    reimbursements: ReimbursementProvider
    profile: ProfileProvider
    career: CareerProvider
    onboarding: OnboardingProvider
    documents: DocumentsProvider


class HRGateway(Protocol):
    def session(self, employee_id: str) -> AbstractContextManager[HRSession]: ...


__all__ = [
    "BenefitsProvider", "CareerProvider", "DirectoryProvider", "DocumentsProvider", "HRGateway", "HRSession",
    "OnboardingProvider", "PayrollProvider", "ProfileProvider", "ReimbursementProvider",
    "TimeTrackingProvider", "VacationProvider",
]
